In [12]:
import tensorflow as tf
import numpy as np

In [13]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [14]:
tensor_2D = tf.constant([[2,3,4,5], [1,2,3, 5]])
print(tensor_2D)

tf.Tensor(
[[2 3 4 5]
 [1 2 3 5]], shape=(2, 4), dtype=int32)


In [15]:
# Creating 4D Tensor

tensor_4D = tf.constant(
    [
        [
            [
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3],
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ]
        ],
        [
            [
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3],
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ]
        ]
    ]
)
print(tensor_4D)

tf.Tensor(
[[[[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]]


 [[[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]

  [[1 2 3]
   [1 2 3]
   [1 2 3]]]], shape=(2, 3, 3, 3), dtype=int32)


In [16]:
x = np.array([1,2,4])
tf_x = tf.convert_to_tensor(x)
print(tf_x)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [17]:
# tf.eye used for Identify Matrix


# eye_tensor = tf.eye(
#     num_rows=None,
#     num_columns=None,
#     batch_shape=None,
#     dtype= tf.dtypes.float32,
#     name=None
# )


identity_matrix = tf.eye(num_rows=4)
print(identity_matrix)
second_identity_matrix = tf.eye(num_rows=3, num_columns=4, dtype= tf.dtypes.bool)
print(second_identity_matrix)

# Now let know what is batch_shape
# batch_shape is used for extending matrix in 3D or Higher Dimension


third_identity_matrix = tf.eye(num_rows=4, batch_shape=[2])
print(third_identity_matrix)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ True False False False]
 [False  True False False]
 [False False  True False]], shape=(3, 4), dtype=bool)
tf.Tensor(
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape=(2, 4, 4), dtype=float32)


In [18]:
# tf.ones method in tensor creates a given dimension size Matrix with every element = 1

ones_tensor = tf.ones(
    [4,5],
    dtype = tf.dtypes.float64,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(4, 5), dtype=float64)


In [19]:
# tf.ones_like this is a method in tensorFlow for creating a ones Tensor of same shape of provided Tensor

onesLike = tf.ones_like(
    [[1,2,3],[2,3,4]],
    dtype = tf.dtypes.float64,
    name = None
)
print(onesLike)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float64)


In [20]:
# tf.zeros_like this is a method in tensorFlow for creating a zeros Tensor of same shape of provided Tensor

zerosLike = tf.zeros_like(
    [[1,2,3],[2,3,4]],
    dtype = tf.dtypes.float64,
    name = None
)
print(zerosLike)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float64)


In [50]:
 # we can generate various random tensor using tf library
# 1. First method is via using normal distribution
# 2. Second method is via using Uniform distribution
# 3. Gaussian Distribution......
# .......so on many-many Distribution we can Have............

random_tensor = tf.random.normal(
    [5,2],
    mean= 100.0,
    stddev=5.0,
    dtype=tf.dtypes.float64,
    seed=None,
    name=None
)
#print(random_tensor)

random_uniform_tensor = tf.random.uniform(
    [1,200],
    minval=0,
    maxval=50,
    dtype=tf.dtypes.float64,
    name=None,
    seed=None
)
x = tf.reduce_sum(random_uniform_tensor)
print(x/200)
# print(random_uniform_tensor)

tf.Tensor(26.040076785921894, shape=(), dtype=float64)


In [22]:
1

1