In [3]:
import tensorflow as tf
import numpy as np

In [22]:
tensor = tf.constant([[1,2,-23,4,5],[-25,6,7,-48,6]])
# for getting range of tensor we can do via
# x = tensor[start:end:stapes]
start = 0
end = 5
stapes = 2
print(tensor[start:end:stapes, :])


tf.Tensor([[1 2 3 4 5]], shape=(1, 5), dtype=int32)


## tf.abs()
#### Convert  a tensor's all value to absolute value
#### we wil use tf.abs() function

In [33]:
# tf.identity is used just for deep copying the data of another tensor
x = tf.identity(tensor)
tf.abs(x)
print(x)

tf.Tensor(
[[1 2 3 4 5]
 [5 6 7 8 6]], shape=(2, 5), dtype=int32)


# Using some mathematical Operation for calculation
#### tf.add(), tf.subtract(), tf.multiply(), tf.divide()

# tf.math.divide_no_nan
#### when we use tf.math.divide_no_nan It gives an error in case when some element get divided by 0